apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: k8gb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: coredns
    helm.sh/chart: coredns-1.15.3
    k8gb-migrated-svc: "true"
  name: k8gb-coredns
spec:
  ports:
  - name: udp-5353
    port: 53
    protocol: UDP
    targetPort: 5353
  selector:
    app.kubernetes.io/instance: k8gb
    app.kubernetes.io/name: coredns
  type: ClusterIP
status:
  loadBalancer: {}
